### ISSUE TITLE
E02: Webpage Content - Mockup Page

### ISSUE THREAD

**Issue by tineriver** [alahele/alahele.github.io#6]

**Comment by ghost** [comment]
![Image](https://user-images.githubusercontent.com/111934550/187562827-24a18cc4-0caa-48f7-950e-c0ca05007ef9.jpg)

**Comment by ghost** [comment]
![Image](https://user-images.githubusercontent.com/111934550/187562865-b62770b1-3385-41ef-a888-a14a52f40047.jpg)

**Comment by ghost** [comment]
![Image](https://user-images.githubusercontent.com/111934550/187562881-838ad84e-4b7c-4b90-a4bb-f673dcc57367.jpg)

**Comment by ghost** [comment]
![Image](https://user-images.githubusercontent.com/111934550/187562894-015912d8-a0c0-4131-95bf-e1bc2cd7f188.jpg)
